apiVersion: v1
kind: ConfigMap
metadata:
  name: ddns-config
data:
  domain-name: example.com
  record-names: subdomain1,subdomain2
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-credentials
type: Opaque
data:
  # These values need to be base64 encoded. Here is a command to convert to base64:
  #echo "something" | base64
  email: bXlAZW1haWwuY29tCg== #my@email.com
  api-key: YWJjMTIzCg== #abc123
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns-update
spec:
  schedule: "0 * * * *"  # Run every hour
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ddns-updater
            image: mrorbitman/cloudflare-ddns-helper:latest #change this to the image you compiled using the kubernetes Dockerfile
            imagePullPolicy: Always
            env:
            - name: CLOUDFLARE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: cloudflare-credentials
                  key: email
            - name: CLOUDFLARE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare-credentials
                  key: api-key
            - name: DOMAIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: ddns-config
                  key: domain-name
            - name: RECORD_NAMES
              valueFrom:
                configMapKeyRef:
                  name: ddns-config
                  key: record-names
          restartPolicy: Never
